ALTER TABLE races ENABLE ROW LEVEL SECURITY;
ALTER TABLE race_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE sql_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE final_submissions ENABLE ROW LEVEL SECURITY;
